### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by bartoszmaka** [bartoszmaka/school-programming#1]
- [ ] Establish DB connection
- [ ] Create table 'Meals' with fields: name, price, available addons
- [ ] Create model 'Order' which sums up all prices
